# Generated by Django 6.0.4 on 2026-04-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='UnknownCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='unknown_cases/', verbose_name='Фото неизвестного корпуса')),
                ('description', models.TextField(blank=True, help_text='Что заметили? Надписи, разъемы, форма и т.д.', verbose_name='Описание (особенности, приметы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Опознан')),
            ],
            options={
                'verbose_name': 'Неизвестный корпус',
                'verbose_name_plural': 'Неизвестные корпуса',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Модель корпуса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100, verbose_name='Предполагаемый производитель')),
                ('model_name', models.CharField(max_length=200, verbose_name='Предполагаемая модель')),
                ('guesser_name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий (почему так решили)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('unknown_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='cases.unknowncase')),
            ],
            options={
                'verbose_name': 'Предположение',
                'verbose_name_plural': 'Предположения',
            },
        ),
    ]
