# Generated by Django 6.0.4 on 2026-04-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unknowncase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unknowncase',
            name='is_resolved',
        ),
        migrations.AlterField(
            model_name='unknowncase',
            name='photo',
            field=models.ImageField(upload_to='unknown_cases/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('unknown_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.unknowncase')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.DeleteModel(
            name='Guess',
        ),
    ]
