# Generated by Django 6.0.4 on 2026-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_unknowncase_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Дополнительное фото 2'),
        ),
        migrations.AddField(
            model_name='case',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Дополнительное фото 3'),
        ),
        migrations.AlterField(
            model_name='case',
            name='photo',
            field=models.ImageField(default='', upload_to='cases_photos/', verbose_name='Основное фото'),
            preserve_default=False,
        ),
    ]
