# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_photo_2_case_photo_3_alter_case_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Дополнительное фото 4'),
        ),
        migrations.AddField(
            model_name='case',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Дополнительное фото 5'),
        ),
        migrations.AddField(
            model_name='case',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='cases_photos/', verbose_name='Дополнительное фото 6'),
        ),
    ]
